"""empty message

Revision ID: 039175f2c2c1
Revises: d91bf2acdd95
Create Date: 2016-02-05 21:38:07.430069

"""

# revision identifiers, used by Alembic.
revision = '039175f2c2c1'
down_revision = 'd91bf2acdd95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('is_google_contact', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'is_google_contact')
    ### end Alembic commands ###
